version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres_aliance
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=aliance_db
    ports:
      - '5432:5432'